# Generated by Django 4.1.3 on 2022-12-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeify', '0002_remove_customuser_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(default=None),
        ),
    ]
