# Generated by Django 4.1.3 on 2022-12-10 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeify', '0008_alter_customuser_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateField()),
                ('deadline', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('reward', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('done', 'Done')], default='to_do', max_length=20)),
                ('emoji', models.CharField(default='none', max_length=50)),
                ('color', models.CharField(default='white', max_length=50)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedUser', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeify.homegroup')),
            ],
        ),
    ]
