# Generated by Django 4.1.3 on 2022-12-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeify', '0009_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('on hold', 'On Hold'), ('done', 'Done')], default='to do', max_length=20),
        ),
    ]
