# Generated by Django 4.1.3 on 2022-12-11 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeify', '0010_alter_task_deadline_alter_task_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
