const WINDOW_WIDTH_MOBILE = 767;
const WINDOW_WIDTH_SMALL = 1300;
const WINDOW_WIDTH_MEDIUM = 1400;
const BASE_URL = 'http://127.0.0.1:8000';
const LOCAL_STORAGE_KEYS = {
    AUTH_TOKEN: 'AUTH_TOKEN',
    LANGUAGE: 'LANGUAGE',
};

export {
    WINDOW_WIDTH_MOBILE,
    WINDOW_WIDTH_SMALL,
    WINDOW_WIDTH_MEDIUM,
    BASE_URL,
    LOCAL_STORAGE_KEYS,
};
