const AUTH_ACTION_TYPES = {
  ERROR: 'ERROR',
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
};

const GROUP_ACTION_TYPES = {
  ADD: 'ADD_GROUP',
  GET_USER_GROUPS: 'GET_USER_GROUPS'
};

export {
  AUTH_ACTION_TYPES,
  GROUP_ACTION_TYPES,
};
